version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: antifraud
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  app:
    build: .
    environment:
      - DB_HOST=db
    depends_on:
      - db

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - C:/AI:/app/models
    environment:
      - DB_HOST=db
    depends_on:
      - db

  ml_worker:
    build: ./api
    volumes:
      - ./api:/app
    environment:
      - DB_HOST=db
    command: ["python", "ml_worker.py"]
    depends_on:
      - db

  frontend:
    build: ./frontend-react
    ports:
      - "3000:5173"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    depends_on:
      - api